/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as GlutenFreeVeganRecipesRouteImport } from './routes/gluten-free-vegan-recipes'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as VeganBreakfastIdeasRouteImport } from './routes/vegan-breakfast-ideas'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthSetupRouteImport } from './routes/auth.setup'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as RecipesIndexRouteImport } from './routes/recipes.index'
import { Route as RecipesIdRouteImport } from './routes/recipes.$id'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as LovableNewsletterSendWeeklyRouteImport } from './routes/lovable/newsletter/send-weekly'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const GlutenFreeVeganRecipesRoute = GlutenFreeVeganRecipesRouteImport.update({
  id: '/gluten-free-vegan-recipes',
  path: '/gluten-free-vegan-recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const VeganBreakfastIdeasRoute = VeganBreakfastIdeasRouteImport.update({
  id: '/vegan-breakfast-ideas',
  path: '/vegan-breakfast-ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSetupRoute = AuthSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIdRoute = RecipesIdRouteImport.update({
  id: '/recipes/$id',
  path: '/recipes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableNewsletterSendWeeklyRoute =
  LovableNewsletterSendWeeklyRouteImport.update({
    id: '/lovable/newsletter/send-weekly',
    path: '/lovable/newsletter/send-weekly',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/gluten-free-vegan-recipes': typeof GlutenFreeVeganRecipesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/vegan-breakfast-ideas': typeof VeganBreakfastIdeasRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/setup': typeof AuthSetupRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/auth/': typeof AuthIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/newsletter/send-weekly': typeof LovableNewsletterSendWeeklyRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gluten-free-vegan-recipes': typeof GlutenFreeVeganRecipesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/vegan-breakfast-ideas': typeof VeganBreakfastIdeasRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/setup': typeof AuthSetupRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/auth': typeof AuthIndexRoute
  '/journal': typeof JournalIndexRoute
  '/recipes': typeof RecipesIndexRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/newsletter/send-weekly': typeof LovableNewsletterSendWeeklyRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/gluten-free-vegan-recipes': typeof GlutenFreeVeganRecipesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/vegan-breakfast-ideas': typeof VeganBreakfastIdeasRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/setup': typeof AuthSetupRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/auth/': typeof AuthIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/newsletter/send-weekly': typeof LovableNewsletterSendWeeklyRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/gluten-free-vegan-recipes'
    | '/sitemap.xml'
    | '/submit'
    | '/unsubscribe'
    | '/vegan-breakfast-ideas'
    | '/admin'
    | '/auth/reset-password'
    | '/auth/setup'
    | '/email/unsubscribe'
    | '/journal/$slug'
    | '/recipes/$id'
    | '/auth/'
    | '/journal/'
    | '/recipes/'
    | '/lovable/email/suppression'
    | '/lovable/newsletter/send-weekly'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/gluten-free-vegan-recipes'
    | '/sitemap.xml'
    | '/submit'
    | '/unsubscribe'
    | '/vegan-breakfast-ideas'
    | '/admin'
    | '/auth/reset-password'
    | '/auth/setup'
    | '/email/unsubscribe'
    | '/journal/$slug'
    | '/recipes/$id'
    | '/auth'
    | '/journal'
    | '/recipes'
    | '/lovable/email/suppression'
    | '/lovable/newsletter/send-weekly'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/gluten-free-vegan-recipes'
    | '/sitemap.xml'
    | '/submit'
    | '/unsubscribe'
    | '/vegan-breakfast-ideas'
    | '/_authenticated/admin'
    | '/auth/reset-password'
    | '/auth/setup'
    | '/email/unsubscribe'
    | '/journal/$slug'
    | '/recipes/$id'
    | '/auth/'
    | '/journal/'
    | '/recipes/'
    | '/lovable/email/suppression'
    | '/lovable/newsletter/send-weekly'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRouteWithChildren
  GlutenFreeVeganRecipesRoute: typeof GlutenFreeVeganRecipesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubmitRoute: typeof SubmitRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  VeganBreakfastIdeasRoute: typeof VeganBreakfastIdeasRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  JournalSlugRoute: typeof JournalSlugRoute
  RecipesIdRoute: typeof RecipesIdRoute
  JournalIndexRoute: typeof JournalIndexRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableNewsletterSendWeeklyRoute: typeof LovableNewsletterSendWeeklyRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gluten-free-vegan-recipes': {
      id: '/gluten-free-vegan-recipes'
      path: '/gluten-free-vegan-recipes'
      fullPath: '/gluten-free-vegan-recipes'
      preLoaderRoute: typeof GlutenFreeVeganRecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vegan-breakfast-ideas': {
      id: '/vegan-breakfast-ideas'
      path: '/vegan-breakfast-ideas'
      fullPath: '/vegan-breakfast-ideas'
      preLoaderRoute: typeof VeganBreakfastIdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/setup': {
      id: '/auth/setup'
      path: '/setup'
      fullPath: '/auth/setup'
      preLoaderRoute: typeof AuthSetupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$id': {
      id: '/recipes/$id'
      path: '/recipes/$id'
      fullPath: '/recipes/$id'
      preLoaderRoute: typeof RecipesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/newsletter/send-weekly': {
      id: '/lovable/newsletter/send-weekly'
      path: '/lovable/newsletter/send-weekly'
      fullPath: '/lovable/newsletter/send-weekly'
      preLoaderRoute: typeof LovableNewsletterSendWeeklyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSetupRoute: typeof AuthSetupRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSetupRoute: AuthSetupRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRouteWithChildren,
  GlutenFreeVeganRecipesRoute: GlutenFreeVeganRecipesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubmitRoute: SubmitRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  VeganBreakfastIdeasRoute: VeganBreakfastIdeasRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  JournalSlugRoute: JournalSlugRoute,
  RecipesIdRoute: RecipesIdRoute,
  JournalIndexRoute: JournalIndexRoute,
  RecipesIndexRoute: RecipesIndexRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableNewsletterSendWeeklyRoute: LovableNewsletterSendWeeklyRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
